"""empty message

Revision ID: 9f5f8ff169a6
Revises: 
Create Date: 2022-10-14 09:39:29.942507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f5f8ff169a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_id', table_name='member')
    op.drop_index('ix_member_idmember', table_name='member')
    op.drop_table('member')
    op.drop_table('trans')
    op.drop_index('ix_koderak_id', table_name='koderak')
    op.drop_index('koderak', table_name='koderak')
    op.drop_table('koderak')
    op.drop_index('ix_kodegenre_id', table_name='kodegenre')
    op.drop_index('kodegenre', table_name='kodegenre')
    op.drop_table('kodegenre')
    op.drop_table('admin')
    op.drop_table('auth')
    op.drop_table('dokter_history')
    op.drop_table('dokter')
    op.drop_index('ix_buku_id', table_name='buku')
    op.drop_index('ix_buku_kodebuku', table_name='buku')
    op.drop_table('buku')
    op.drop_table('admin_history')
    op.drop_index('ix_transaksi_id', table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_table('pasien')
    op.drop_table('pasien_history')
    op.drop_index('ix_admin_perpus_id', table_name='admin_perpus')
    op.drop_table('admin_perpus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_perpus',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=99), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_admin_perpus_id', 'admin_perpus', ['id'], unique=False)
    op.create_table('pasien_history',
    sa.Column('no_pasien_history', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('no_pasien', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_pasien', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('alamat_pasien', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], name='pasien_history_ibfk_1'),
    sa.PrimaryKeyConstraint('no_pasien_history'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pasien',
    sa.Column('no_pasien', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_auth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_pasien', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('alamat_pasien', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('status_diperiksa', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], name='pasien_ibfk_1'),
    sa.PrimaryKeyConstraint('no_pasien'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('transaksi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('idmember', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('kodebuku', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('tgl_pinjam', sa.DATE(), nullable=False),
    sa.Column('tgl_kembali', sa.DATE(), nullable=False),
    sa.Column('idadmin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idadmin'], ['admin_perpus.id'], name='transaksi_ibfk_3'),
    sa.ForeignKeyConstraint(['idmember'], ['member.idmember'], name='transaksi_ibfk_1'),
    sa.ForeignKeyConstraint(['kodebuku'], ['buku.kodebuku'], name='transaksi_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_transaksi_id', 'transaksi', ['id'], unique=False)
    op.create_table('admin_history',
    sa.Column('id_admin_history', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_admin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_admin', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('jabatan', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['admin.id_admin'], name='admin_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id_admin_history'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('buku',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kodebuku', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('judul', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('genre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lokasi', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_buku_kodebuku', 'buku', ['kodebuku'], unique=False)
    op.create_index('ix_buku_id', 'buku', ['id'], unique=False)
    op.create_table('dokter',
    sa.Column('id_dokter', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_auth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_dokter', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('hari_kerja', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('jam_kerja', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('status_pemeriksaan', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('kuota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], name='dokter_ibfk_1'),
    sa.PrimaryKeyConstraint('id_dokter'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('dokter_history',
    sa.Column('no_dokter_history', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_dokter', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_dokter', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('hari_kerja', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('jam_kerja', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('kuota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], name='dokter_history_ibfk_1'),
    sa.PrimaryKeyConstraint('no_dokter_history'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth',
    sa.Column('id_auth', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status_auth', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id_auth'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('id_admin', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_auth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('nama_admin', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('jabatan', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], name='admin_ibfk_1'),
    sa.PrimaryKeyConstraint('id_admin'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('kodegenre',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kodegenre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('namagenre', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('kodegenre', 'kodegenre', ['kodegenre'], unique=False)
    op.create_index('ix_kodegenre_id', 'kodegenre', ['id'], unique=False)
    op.create_table('koderak',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('koderak', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('namarak', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('koderak', 'koderak', ['koderak'], unique=False)
    op.create_index('ix_koderak_id', 'koderak', ['id'], unique=False)
    op.create_table('trans',
    sa.Column('id_trans', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_dokter', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('no_pasien', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_bayar', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('status_checking_dokter', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('resep_dokter', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('harga_bayar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('keluhan', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('flag', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('updated_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], name='trans_ibfk_1'),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], name='trans_ibfk_2'),
    sa.PrimaryKeyConstraint('id_trans'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('member',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('idmember', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('nik', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('jenis_kelamin', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=99), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_member_idmember', 'member', ['idmember'], unique=False)
    op.create_index('ix_member_id', 'member', ['id'], unique=False)
    # ### end Alembic commands ###
